### ISSUE TITLE
Cluster shutdown fails in batch mode on Python >3.8

### ISSUE THREAD

**Issue by kmpaul** [dask/dask-mpi#87]
**What happened**:

When Dask-MPI is used in *batch* mode (i.e., using `initialize()`), it does not properly shut down the scheduler and worker processes when the *client* script completes.

**What you expected to happen**:

When the *client* script completes, the scheduler and worker processes should be shut down without error.

**Minimal Complete Verifiable Example**:

In a script called `client.py`:

```python
from distributed import Client
from dask_mpi import initialize

initialize()

with Client() as c:
    assert c.submit(lambda x: x + 1, 10).result() == 11
```

Then run this with `mpirun` as:

```bash
mpirun -n 4 python client.py
```

This will result in the following errors and hanging processes.

<details>
<summary>Output & Error Messages</summary>
2022-04-19 15:44:59,709 - distributed.scheduler - INFO - State start
2022-04-19 15:44:59,712 - distributed.scheduler - INFO - Clear task state
2022-04-19 15:44:59,713 - distributed.scheduler - INFO -   Scheduler at:  tcp://192.168.1.27:64417
2022-04-19 15:44:59,713 - distributed.scheduler - INFO -   dashboard at:                    :64416
2022-04-19 15:44:59,730 - distributed.worker - INFO -       Start worker at:   tcp://192.168.1.27:64418
2022-04-19 15:44:59,730 - distributed.worker - INFO -          Listening to:   tcp://192.168.1.27:64418
2022-04-19 15:44:59,730 - distributed.worker - INFO -       Start worker at:   tcp://192.168.1.27:64419
2022-04-19 15:44:59,730 - distributed.worker - INFO -          dashboard at:         192.168.1.27:64422
2022-04-19 15:44:59,730 - distributed.worker - INFO - Waiting to connect to:   tcp://192.168.1.27:64417
2022-04-19 15:44:59,730 - distributed.worker - INFO - -------------------------------------------------
2022-04-19 15:44:59,730 - distributed.worker - INFO -          Listening to:   tcp://192.168.1.27:64419
2022-04-19 15:44:59,731 - distributed.worker - INFO -          dashboard at:         192.168.1.27:64423
2022-04-19 15:44:59,730 - distributed.worker - INFO -               Threads:                          1
2022-04-19 15:44:59,731 - distributed.worker - INFO -                Memory:                   2.00 GiB
2022-04-19 15:44:59,731 - distributed.worker - INFO - Waiting to connect to:   tcp://192.168.1.27:64417
2022-04-19 15:44:59,731 - distributed.worker - INFO -       Local Directory: /Users/kpaul/tst/dask-worker-space/worker-ljhbwdiz
2022-04-19 15:44:59,731 - distributed.worker - INFO - -------------------------------------------------
2022-04-19 15:44:59,731 - distributed.worker - INFO - -------------------------------------------------
2022-04-19 15:44:59,731 - distributed.worker - INFO -               Threads:                          1
2022-04-19 15:44:59,731 - distributed.worker - INFO -                Memory:                   2.00 GiB
2022-04-19 15:44:59,731 - distributed.worker - INFO -       Local Directory: /Users/kpaul/tst/dask-worker-space/worker-xtuties_
2022-04-19 15:44:59,731 - distributed.worker - INFO - -------------------------------------------------
2022-04-19 15:44:59,750 - distributed.scheduler - INFO - Receive client connection: Client-f6204526-c029-11ec-a0ca-acde48001122
2022-04-19 15:44:59,762 - distributed.core - INFO - Starting established connection
2022-04-19 15:44:59,764 - distributed.scheduler - INFO - Register worker <WorkerState 'tcp://192.168.1.27:64418', name: 3, status: undefined, memory: 0, processing: 0>
2022-04-19 15:44:59,765 - distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.27:64418
2022-04-19 15:44:59,765 - distributed.core - INFO - Starting established connection
2022-04-19 15:44:59,766 - distributed.scheduler - INFO - Register worker <WorkerState 'tcp://192.168.1.27:64419', name: 2, status: undefined, memory: 0, processing: 0>
2022-04-19 15:44:59,766 - distributed.worker - INFO -         Registered to:   tcp://192.168.1.27:64417
2022-04-19 15:44:59,766 - distributed.worker - INFO - -------------------------------------------------
2022-04-19 15:44:59,767 - distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.27:64419
2022-04-19 15:44:59,767 - distributed.core - INFO - Starting established connection
2022-04-19 15:44:59,768 - distributed.core - INFO - Starting established connection
2022-04-19 15:44:59,767 - distributed.worker - INFO -         Registered to:   tcp://192.168.1.27:64417
2022-04-19 15:44:59,768 - distributed.worker - INFO - -------------------------------------------------
2022-04-19 15:44:59,769 - distributed.core - INFO - Starting established connection
2022-04-19 15:44:59,870 - distributed.scheduler - INFO - Remove client Client-f6204526-c029-11ec-a0ca-acde48001122
2022-04-19 15:44:59,870 - distributed.scheduler - INFO - Remove client Client-f6204526-c029-11ec-a0ca-acde48001122
2022-04-19 15:44:59,871 - distributed.scheduler - INFO - Close client connection: Client-f6204526-c029-11ec-a0ca-acde48001122
Exception ignored in atexit callback: <function send_close_signal at 0x10f8085e0>
Traceback (most recent call last):
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/site-packages/dask_mpi/core.py", line 159, in send_close_signal
    with Client() as c:
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/site-packages/distributed/client.py", line 943, in __init__
    self.start(timeout=timeout)
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/site-packages/distributed/client.py", line 1101, in start
    sync(self.loop, self._start, **kwargs)
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/site-packages/distributed/utils.py", line 376, in sync
    raise exc.with_traceback(tb)
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/site-packages/distributed/utils.py", line 349, in f
    result = yield future
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/site-packages/distributed/client.py", line 1193, in _start
    await self._ensure_connected(timeout=timeout)
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/site-packages/distributed/client.py", line 1256, in _ensure_connected
    comm = await connect(
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/site-packages/distributed/comm/core.py", line 289, in connect
    comm = await asyncio.wait_for(
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/site-packages/distributed/comm/tcp.py", line 439, in connect
    stream = await self.client.connect(
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/site-packages/distributed/comm/tcp.py", line 424, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/asyncio/base_events.py", line 818, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/Users/kpaul/Software/miniconda3/envs/t/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
</details>

**Anything else we need to know?**:

I believe this is due to changes in `asyncio` that occurred with the release of Python 3.9 (and continues in 3.10).  Dask-MPI depends upon calling a function to shutdown the dask cluster *at exit* (i.e., via the `atexit` module).  But it appears that the changes in CPython prevent the calling of an `asyncio`-dependent function *at exit*, resulting in the above `RuntimeError: cannot schedule new futures after interpreter shutdown`.

**Environment**:

- Dask version:  `2022.4.1`
- Python version:  `3.10.4`
- Operating System:  Linux / MacOS
- Install method (conda, pip, source):  conda

**Comment by kmpaul** [comment]
I believe that the appropriate solution to this problem is to remove the explicit `atexit`-registered function and require that the user call `Client.shutdown()` at the end of their script.

And I think there are additional simplifications that can be done following this change, but I need some time to think about it before writing anything more down.

**Comment by kmpaul** [comment]
One note.  The `distributed.comm.core.CommClosedError` errors can be avoided by calling `Client.shutdown()` instead of Dask-MPI's `core.send_close_signal()`.  However, if we use:

```python
def send_close_signal():
    with Client() as c:
        c.shutdown()
```

this will still fail with Python >3.8 when used with `atexit` because the loop will be closed by the time `send_close_signal` is called.

**Comment by kmpaul** [comment]
Note that even with the merge of #89, these errors still occur.

**Comment by kmpaul** [comment]
One potential solution to this is to *not* use an `atexit` handler to shut down the cluster.  Instead, require that the user shutdown the cluster *manually* at the end of the script.  This would effectively mean that the canonical use case of `dask_mpi.initialize()` would change from:

```python
initialize()

with Client() as c:
    # dask stuff
```

with the `Client.shutdown()` method called by the `atexit` handler, to

```python
initialize()

with Client() as c:
    # dask stuff
    c.shutdown()
```

with the `c.shutdown()` call above being *required* or the process will hang.  We could even encapsulate the `c.shutdown()` in a function that bookends the `initialize()` method like so:

```python
def finalize(...):
    with Client() as c:
        c.shutdown()
```

so that the dask-mpi client script might look like:

```python
initialize()

with Client() as c:
    # dask stuff

# maybe more stuff

finalize()
```

However, this *definitely* breaks backwards compatibility.  It does fix the above hanging, though.  **Is this acceptable?**

CC @mrocklin @jacobtomlinson

**Comment by kmpaul** [comment]
## Possible API changes

If we have to break backwards compatibility, then I want to suggest some other changes that might work with the suggested changes above.

With @joezuntz's changes to allow users to pass into Dask-MPI an existing MPI communicator object and turn off explicit "shutdown" of the Dask cluster, there is now a foreseeable mechanism for stopping/restarting a Dask-MPI cluster from within a client batch process.  With my understanding, I think this requires 3 components:

1. a Dask-MPI `initialize()` function that starts the scheduler and worker processes and subsequently block on all MPII ranks except the *client* rank (e.g., rank==1),
2. a Dask-MPI `is_client()` function that returns `True` when the MPI rank is equal to the *client* rank, and
3. a Dask-MPI `finalize()` function that stops the scheduler and worker processes.

The general outline of how to use these three functions together would be like so:

```python
from dask_mpi import initialize, is_client, finalize

initialize()  # Blocks scheduler and worker MPI ranks HERE!!!

if is_client():
    # Do your client dask operations here
    # When the scheduler and worker MPI ranks unblock due to the finalize call below,
    # this section will be skipped by the scheduler and worker MPI ranks

finalize() # Everything after this can act like a normal mpi4py script
```

...This whole thing is starting to look to me like a context manager, no?

**Comment by jacobtomlinson** [comment]
I wonder if using a context manager would feel more natural here.

```python
def initialize(...):
    with Client() as c:
        ...
```

**Comment by kmpaul** [comment]
@jacobtomlinson:  Yeah.  I was thinking of something like:

```
with MPICluster(...) as cluster, Client(cluster) as c:
    if cluster.is_client():
        ...
```

where the `MPICluster(...)` object would essentially be the `initialize(...)` method, except turned into a context manager with `finalize()` being called in `__exit__()`.

...but I don't like the nested `if` pattern.  It's fiddly and prone to errors, I think.

**Comment by jacobtomlinson** [comment]
This is kind of where I was going with the `MPIRunner` class in https://github.com/dask/distributed/pull/4710 and https://github.com/dask/dask-mpi/pull/69. The `Cluster` class doesn't quite line up with the use case here, given that the job and resources already exist and we are trying to populate them, rather than create them in the first place. This is why I tried to add `Runner` and a sibling to `Cluster` for this use case.

However @mrocklin suggested that `Cluster` would be a fine way to implement it and adding a new base class only increases complexity. So perhaps it would be good to resurrect #69 but base it on `Cluster` instead.

**Comment by zhiyuli** [comment]
same issue here. I will try python3.8 for now

**Comment by evgri243** [comment]
Experience the same.

Can we think of some temporary workaround here? Maybe closing the MPI cluster manually after the c.shutdown or "request killing the workers/check worker count/repeat again if needed/close scheduler"? I do already implement exiting logic manually, so that I don't mind adding a few more lines...

**Comment by kmpaul** [comment]
Yeah. If you have time for a PR, that would be great, @evgri243!
